loose_change = [
    {"denomination":"quarter","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"dime","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"quarter","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"dime","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"quarter","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"dime","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"dime","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"quarter","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"nickel","year":"2014"},
    {"denomination":"dime","year":"2014"},
    {"denomination":"nickel","year":"2014"},
]
# How many stacks of N units can we make for each denomination of coin?
